server:
  port: 8881
  servlet:
    context-path: /api

spring:
  application:
    name: employee-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://192.168.100.197:5432/nkbost-employee-db
    username: postgres
    password: Postgres2025!
    driver-class-name: org.postgresql.Driver
    connectionTimeout: 30000
    idleTimeout: 30000
    max-open-prepared-statements: 250
    maxLifetime: 2000000
    maximumPoolSize: 5
    minimumIdle: 3
    pool-prepared-statements: true
    poolName: SpringBootHikariCP
    hikari:
      connection-timeout: '60000'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration #, classpath:db/callback
---
spring:
  application:
    name: employee-service
  profiles:
    active: hom
  datasource:
    url: jdbc:postgresql://192.168.100.197:5432/nkbost-employee-db
    username: postgres
    password: Postgres2025!
    driver-class-name: org.postgresql.Driver
    connectionTimeout: 30000
    idleTimeout: 30000
    max-open-prepared-statements: 250
    maxLifetime: 2000000
    maximumPoolSize: 5
    minimumIdle: 3
    pool-prepared-statements: true
    poolName: SpringBootHikariCP
    hikari:
      connection-timeout: '60000'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration #, classpath:db/callback
---
spring:
  application:
    name: employee-service
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://192.168.100.197:5432/nkbost-employee-db
    username: postgres
    password: Postgres2025!
    driver-class-name: org.postgresql.Driver
    connectionTimeout: 30000
    idleTimeout: 30000
    max-open-prepared-statements: 250
    maxLifetime: 2000000
    maximumPoolSize: 5
    minimumIdle: 3
    pool-prepared-statements: true
    poolName: SpringBootHikariCP
    hikari:
      connection-timeout: '60000'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration #, classpath:db/callback

springdoc:
  api-docs:
    enabled: true
    swagger-ui:
      enabled: true

resilience4j:
  retry:
    instances:
      employeeService:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      employeeService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  bulkhead:
    instances:
      employeeService:
        max-concurrent-calls: 10

logging:
  level:
    org.springframework.cloud.config.client: DEBUG